---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/links":
    get:
      summary: GET Links
      tags:
      - Link
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer {key}
        schema:
          type: string
      responses:
        '200':
          description: 성공
        '401':
          description: 실패
    post:
      summary: CREATE Links
      tags:
      - Link
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer {key}
        schema:
          type: string
      responses:
        '201':
          description: 성공
        '401':
          description: 인증 실패
        '422':
          description: 파라메터 부족으로 실패
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 구글
                url:
                  type: string
                  example: https://google.com
                tag_list:
                  type: string
                  example: 개발자
              required:
              - name
              - url
  "/links/{id}":
    get:
      summary: GET Link
      tags:
      - Link
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer {key}
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 성공
        '401':
          description: 인증 실패
        '404':
          description: 링크 찾기 실패
    patch:
      summary: UPDATE Link
      tags:
      - Link
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer {key}
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 성공
        '401':
          description: 인증 실패
        '404':
          description: 링크 찾기 실패
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 구글
                url:
                  type: string
                  example: https://google.com
                tag_list:
                  type: string
                  example: 개발자
              required:
              - name
              - url
    delete:
      summary: DELETE Link
      tags:
      - Link
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Bearer {key}
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: 성공
        '401':
          description: 인증 실패
        '404':
          description: 링크 찾기 실패
  "/login":
    post:
      summary: Login
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: 로그인 성공
        '401':
          description: 로그인 실패
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: tjstlr2010@gmail.com
                password:
                  type: string
                  example: qwer1234
              required:
              - email
              - password
servers:
- url: http://localhost:3000
- url: https://linkcloud-rails.herokuapp.com
